[project]
name = "ntica-data"
version = "0.1.0"
description = "Supports de TD pour NTICA"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.0",
    "pymupdf>=1.26.0",
]
